// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: orders/orderspb/orders.proto

package orderspb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AllRestaurantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllRestaurantRequest) Reset() {
	*x = AllRestaurantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_orderspb_orders_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllRestaurantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllRestaurantRequest) ProtoMessage() {}

func (x *AllRestaurantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orderspb_orders_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllRestaurantRequest.ProtoReflect.Descriptor instead.
func (*AllRestaurantRequest) Descriptor() ([]byte, []int) {
	return file_orders_orderspb_orders_proto_rawDescGZIP(), []int{0}
}

type AllCuisineRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllCuisineRequest) Reset() {
	*x = AllCuisineRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_orderspb_orders_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllCuisineRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllCuisineRequest) ProtoMessage() {}

func (x *AllCuisineRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orderspb_orders_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllCuisineRequest.ProtoReflect.Descriptor instead.
func (*AllCuisineRequest) Descriptor() ([]byte, []int) {
	return file_orders_orderspb_orders_proto_rawDescGZIP(), []int{1}
}

type AllStateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AllStateRequest) Reset() {
	*x = AllStateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_orderspb_orders_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStateRequest) ProtoMessage() {}

func (x *AllStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orderspb_orders_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStateRequest.ProtoReflect.Descriptor instead.
func (*AllStateRequest) Descriptor() ([]byte, []int) {
	return file_orders_orderspb_orders_proto_rawDescGZIP(), []int{2}
}

type AllRestaurantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllRestaurant map[string]int64 `protobuf:"bytes,1,rep,name=allRestaurant,proto3" json:"allRestaurant,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *AllRestaurantResponse) Reset() {
	*x = AllRestaurantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_orderspb_orders_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllRestaurantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllRestaurantResponse) ProtoMessage() {}

func (x *AllRestaurantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orderspb_orders_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllRestaurantResponse.ProtoReflect.Descriptor instead.
func (*AllRestaurantResponse) Descriptor() ([]byte, []int) {
	return file_orders_orderspb_orders_proto_rawDescGZIP(), []int{3}
}

func (x *AllRestaurantResponse) GetAllRestaurant() map[string]int64 {
	if x != nil {
		return x.AllRestaurant
	}
	return nil
}

type AllCuisineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllCuisine map[string]int64 `protobuf:"bytes,1,rep,name=allCuisine,proto3" json:"allCuisine,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *AllCuisineResponse) Reset() {
	*x = AllCuisineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_orderspb_orders_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllCuisineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllCuisineResponse) ProtoMessage() {}

func (x *AllCuisineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orderspb_orders_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllCuisineResponse.ProtoReflect.Descriptor instead.
func (*AllCuisineResponse) Descriptor() ([]byte, []int) {
	return file_orders_orderspb_orders_proto_rawDescGZIP(), []int{4}
}

func (x *AllCuisineResponse) GetAllCuisine() map[string]int64 {
	if x != nil {
		return x.AllCuisine
	}
	return nil
}

type AllCuisine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllCuisine map[string]int64 `protobuf:"bytes,1,rep,name=allCuisine,proto3" json:"allCuisine,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
}

func (x *AllCuisine) Reset() {
	*x = AllCuisine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_orderspb_orders_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllCuisine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllCuisine) ProtoMessage() {}

func (x *AllCuisine) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orderspb_orders_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllCuisine.ProtoReflect.Descriptor instead.
func (*AllCuisine) Descriptor() ([]byte, []int) {
	return file_orders_orderspb_orders_proto_rawDescGZIP(), []int{5}
}

func (x *AllCuisine) GetAllCuisine() map[string]int64 {
	if x != nil {
		return x.AllCuisine
	}
	return nil
}

type AllStateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AllState map[string]*AllCuisine `protobuf:"bytes,1,rep,name=allState,proto3" json:"allState,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AllStateResponse) Reset() {
	*x = AllStateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orders_orderspb_orders_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllStateResponse) ProtoMessage() {}

func (x *AllStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_orderspb_orders_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllStateResponse.ProtoReflect.Descriptor instead.
func (*AllStateResponse) Descriptor() ([]byte, []int) {
	return file_orders_orderspb_orders_proto_rawDescGZIP(), []int{6}
}

func (x *AllStateResponse) GetAllState() map[string]*AllCuisine {
	if x != nil {
		return x.AllState
	}
	return nil
}

var File_orders_orderspb_orders_proto protoreflect.FileDescriptor

var file_orders_orderspb_orders_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x70,
	0x62, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0x16, 0x0a, 0x14, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73,
	0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13,
	0x0a, 0x11, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xb1, 0x01, 0x0a, 0x15, 0x41, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x56, 0x0a, 0x0d, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x30, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75,
	0x72, 0x61, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x61, 0x6c, 0x6c, 0x52, 0x65,
	0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x1a, 0x40, 0x0a, 0x12, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10,
	0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x9f, 0x01, 0x0a, 0x12, 0x41,
	0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x4a, 0x0a, 0x0a, 0x61, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x41,
	0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x1a, 0x3d, 0x0a,
	0x0f, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x8f, 0x01, 0x0a,
	0x0a, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x12, 0x42, 0x0a, 0x0a, 0x61,
	0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73,
	0x69, 0x6e, 0x65, 0x2e, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x0a, 0x61, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x1a,
	0x3d, 0x0a, 0x0f, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xa7,
	0x01, 0x0a, 0x10, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x42, 0x0a, 0x08, 0x61, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x41,
	0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x61,
	0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x1a, 0x4f, 0x0a, 0x0d, 0x41, 0x6c, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x28, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x2e, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xf0, 0x01, 0x0a, 0x0d, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x51, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x1c,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x74, 0x61,
	0x75, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x74, 0x61, 0x75, 0x72,
	0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x48, 0x0a,
	0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x12, 0x19,
	0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69,
	0x6e, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x2e, 0x41, 0x6c, 0x6c, 0x43, 0x75, 0x69, 0x73, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x41, 0x6c,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x17, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e,
	0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x18, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x2e, 0x41, 0x6c, 0x6c, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x11, 0x5a, 0x0f, 0x6f,
	0x72, 0x64, 0x65, 0x72, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orders_orderspb_orders_proto_rawDescOnce sync.Once
	file_orders_orderspb_orders_proto_rawDescData = file_orders_orderspb_orders_proto_rawDesc
)

func file_orders_orderspb_orders_proto_rawDescGZIP() []byte {
	file_orders_orderspb_orders_proto_rawDescOnce.Do(func() {
		file_orders_orderspb_orders_proto_rawDescData = protoimpl.X.CompressGZIP(file_orders_orderspb_orders_proto_rawDescData)
	})
	return file_orders_orderspb_orders_proto_rawDescData
}

var file_orders_orderspb_orders_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_orders_orderspb_orders_proto_goTypes = []interface{}{
	(*AllRestaurantRequest)(nil),  // 0: orders.AllRestaurantRequest
	(*AllCuisineRequest)(nil),     // 1: orders.AllCuisineRequest
	(*AllStateRequest)(nil),       // 2: orders.AllStateRequest
	(*AllRestaurantResponse)(nil), // 3: orders.AllRestaurantResponse
	(*AllCuisineResponse)(nil),    // 4: orders.AllCuisineResponse
	(*AllCuisine)(nil),            // 5: orders.AllCuisine
	(*AllStateResponse)(nil),      // 6: orders.AllStateResponse
	nil,                           // 7: orders.AllRestaurantResponse.AllRestaurantEntry
	nil,                           // 8: orders.AllCuisineResponse.AllCuisineEntry
	nil,                           // 9: orders.AllCuisine.AllCuisineEntry
	nil,                           // 10: orders.AllStateResponse.AllStateEntry
}
var file_orders_orderspb_orders_proto_depIdxs = []int32{
	7,  // 0: orders.AllRestaurantResponse.allRestaurant:type_name -> orders.AllRestaurantResponse.AllRestaurantEntry
	8,  // 1: orders.AllCuisineResponse.allCuisine:type_name -> orders.AllCuisineResponse.AllCuisineEntry
	9,  // 2: orders.AllCuisine.allCuisine:type_name -> orders.AllCuisine.AllCuisineEntry
	10, // 3: orders.AllStateResponse.allState:type_name -> orders.AllStateResponse.AllStateEntry
	5,  // 4: orders.AllStateResponse.AllStateEntry.value:type_name -> orders.AllCuisine
	0,  // 5: orders.OrdersService.GetAllRestaurant:input_type -> orders.AllRestaurantRequest
	1,  // 6: orders.OrdersService.GetAllCuisine:input_type -> orders.AllCuisineRequest
	2,  // 7: orders.OrdersService.GetAllState:input_type -> orders.AllStateRequest
	3,  // 8: orders.OrdersService.GetAllRestaurant:output_type -> orders.AllRestaurantResponse
	4,  // 9: orders.OrdersService.GetAllCuisine:output_type -> orders.AllCuisineResponse
	6,  // 10: orders.OrdersService.GetAllState:output_type -> orders.AllStateResponse
	8,  // [8:11] is the sub-list for method output_type
	5,  // [5:8] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_orders_orderspb_orders_proto_init() }
func file_orders_orderspb_orders_proto_init() {
	if File_orders_orderspb_orders_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orders_orderspb_orders_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllRestaurantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orders_orderspb_orders_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllCuisineRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orders_orderspb_orders_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllStateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orders_orderspb_orders_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllRestaurantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orders_orderspb_orders_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllCuisineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orders_orderspb_orders_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllCuisine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orders_orderspb_orders_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllStateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orders_orderspb_orders_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_orderspb_orders_proto_goTypes,
		DependencyIndexes: file_orders_orderspb_orders_proto_depIdxs,
		MessageInfos:      file_orders_orderspb_orders_proto_msgTypes,
	}.Build()
	File_orders_orderspb_orders_proto = out.File
	file_orders_orderspb_orders_proto_rawDesc = nil
	file_orders_orderspb_orders_proto_goTypes = nil
	file_orders_orderspb_orders_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// OrdersServiceClient is the client API for OrdersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrdersServiceClient interface {
	GetAllRestaurant(ctx context.Context, in *AllRestaurantRequest, opts ...grpc.CallOption) (*AllRestaurantResponse, error)
	GetAllCuisine(ctx context.Context, in *AllCuisineRequest, opts ...grpc.CallOption) (*AllCuisineResponse, error)
	GetAllState(ctx context.Context, in *AllStateRequest, opts ...grpc.CallOption) (*AllStateResponse, error)
}

type ordersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrdersServiceClient(cc grpc.ClientConnInterface) OrdersServiceClient {
	return &ordersServiceClient{cc}
}

func (c *ordersServiceClient) GetAllRestaurant(ctx context.Context, in *AllRestaurantRequest, opts ...grpc.CallOption) (*AllRestaurantResponse, error) {
	out := new(AllRestaurantResponse)
	err := c.cc.Invoke(ctx, "/orders.OrdersService/GetAllRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersServiceClient) GetAllCuisine(ctx context.Context, in *AllCuisineRequest, opts ...grpc.CallOption) (*AllCuisineResponse, error) {
	out := new(AllCuisineResponse)
	err := c.cc.Invoke(ctx, "/orders.OrdersService/GetAllCuisine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ordersServiceClient) GetAllState(ctx context.Context, in *AllStateRequest, opts ...grpc.CallOption) (*AllStateResponse, error) {
	out := new(AllStateResponse)
	err := c.cc.Invoke(ctx, "/orders.OrdersService/GetAllState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrdersServiceServer is the server API for OrdersService service.
type OrdersServiceServer interface {
	GetAllRestaurant(context.Context, *AllRestaurantRequest) (*AllRestaurantResponse, error)
	GetAllCuisine(context.Context, *AllCuisineRequest) (*AllCuisineResponse, error)
	GetAllState(context.Context, *AllStateRequest) (*AllStateResponse, error)
}

// UnimplementedOrdersServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrdersServiceServer struct {
}

func (*UnimplementedOrdersServiceServer) GetAllRestaurant(context.Context, *AllRestaurantRequest) (*AllRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllRestaurant not implemented")
}
func (*UnimplementedOrdersServiceServer) GetAllCuisine(context.Context, *AllCuisineRequest) (*AllCuisineResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllCuisine not implemented")
}
func (*UnimplementedOrdersServiceServer) GetAllState(context.Context, *AllStateRequest) (*AllStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllState not implemented")
}

func RegisterOrdersServiceServer(s *grpc.Server, srv OrdersServiceServer) {
	s.RegisterService(&_OrdersService_serviceDesc, srv)
}

func _OrdersService_GetAllRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServiceServer).GetAllRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orders.OrdersService/GetAllRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServiceServer).GetAllRestaurant(ctx, req.(*AllRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersService_GetAllCuisine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllCuisineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServiceServer).GetAllCuisine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orders.OrdersService/GetAllCuisine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServiceServer).GetAllCuisine(ctx, req.(*AllCuisineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrdersService_GetAllState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrdersServiceServer).GetAllState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/orders.OrdersService/GetAllState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrdersServiceServer).GetAllState(ctx, req.(*AllStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrdersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "orders.OrdersService",
	HandlerType: (*OrdersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllRestaurant",
			Handler:    _OrdersService_GetAllRestaurant_Handler,
		},
		{
			MethodName: "GetAllCuisine",
			Handler:    _OrdersService_GetAllCuisine_Handler,
		},
		{
			MethodName: "GetAllState",
			Handler:    _OrdersService_GetAllState_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "orders/orderspb/orders.proto",
}
